In [1]:
%autosave 2

Autosaving every 2 seconds


In [3]:
x = 10
y = 5
z = x + y
z

15

In [5]:
z * 3

45

In [6]:
import numpy as np

In [14]:
li = [1, 2, 3, 0, 5, 77]
a = np.array(li)
a.dtype

dtype('int64')

In [13]:
np.array([1, 2, 'abc', None])

array([1, 2, 'abc', None], dtype=object)

In [19]:
a = np.array([1, 2, 3, 4, 5], dtype=int)
a

array([1, 2, 3, 4, 5])

In [22]:
a = np.array([1, 2, 3, 4, 5, 128], dtype=np.int8)
a

array([   1,    2,    3,    4,    5, -128], dtype=int8)

In [23]:
a = np.array([1, 2, 3, 4, 5, 128, 256], dtype=np.uint8)
a

array([  1,   2,   3,   4,   5, 128,   0], dtype=uint8)

In [25]:
a = np.array([1.1, 2, 3])
a.dtype

dtype('float64')

In [29]:
a = np.array([1.123456789, 2, 3], dtype=np.float16)
a

array([1.123, 2.   , 3.   ], dtype=float16)

In [27]:
a = np.array([1.1 + 3j, 2, 3])
a.dtype

dtype('complex128')

In [30]:
a = np.array(['abc', 'xyz', 'a'])
a

array(['abc', 'xyz', 'a'], dtype='<U3')

In [31]:
a = np.array([b'abc', b'xyz', b'a'])
a

array([b'abc', b'xyz', b'a'], dtype='|S3')

In [32]:
a = np.array([True, False, True, True])
a.dtype

dtype('bool')

In [34]:
a = np.array([1, 'abc', '', None, True], dtype=bool)
a

array([ True,  True, False, False,  True])

In [35]:
type(a)

numpy.ndarray

In [37]:
np.zeros(5, dtype=bool)

array([False, False, False, False, False])

In [38]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [43]:
a = np.zeros((10, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
a = np.ones(5, dtype=np.uint8)
a

array([1, 1, 1, 1, 1], dtype=uint8)

In [46]:
np.ones(6, dtype=str)

array(['1', '1', '1', '1', '1', '1'], dtype='<U1')

In [53]:
np.empty(7, dtype=np.float32)

array([-7.8637336e+37,  3.0929460e-41, -1.5018800e+37,  3.0929460e-41,
        1.4012985e-45,  0.0000000e+00,            nan], dtype=float32)

In [56]:
np.full(10, 2, dtype=np.complex)

array([2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j,
       2.+0.j, 2.+0.j])

In [57]:
2 * np.ones(10, dtype=complex)

array([2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j, 2.+0.j,
       2.+0.j, 2.+0.j])

In [59]:
5 * [1, 2]

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [62]:
5 * np.array([1, 2, 3])

array([ 5, 10, 15])

In [63]:
5 + np.ones(4)

array([6., 6., 6., 6.])

In [64]:
np.array([-1, -2, -3]) + np.array([3, 2, 1])

array([ 2,  0, -2])

In [66]:
np.arange(10, dtype=np.float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
np.arange(2, 10, dtype=np.float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [69]:
np.arange(0.5, 1.5, 0.1)

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4])

In [ ]:
# for (int i = 0; i < 10; i++)
# double x = i * 0.1

# for (double i = 0; i < 1.0; i += 0.1)

In [70]:
np.arange(0, 2 + 1/3, 1/3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333])

In [72]:
np.arange(0, 2.00000001, 1/3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [73]:
a = 0
b = 2
step = 1 / 3

In [74]:
np.arange(a, b + 0.5 * step, step)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [75]:
np.linspace(0, 2, 7)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [76]:
np.logspace(0, 2, 3)

array([  1.,  10., 100.])

In [77]:
10 ** np.linspace(0, 2, 3)

array([  1.,  10., 100.])

In [78]:
np.logspace(0, 2, 3, base=2)

array([1., 2., 4.])

In [79]:
np.logspace(0, 2, 3, dtype=int)

array([  1,  10, 100])

In [80]:
np.sin(np.linspace(0, 2 * np.pi, 10))

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [81]:
np.log(np.arange(1, 10))

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [83]:
np.log10(np.arange(1, 11))

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [84]:
np.log2([2, 4, 8, 16, 0.5])

array([ 1.,  2.,  3.,  4., -1.])

In [85]:
np.round(np.logspace(0, 1, 5))

array([ 1.,  2.,  3.,  6., 10.])

In [86]:
import math

In [87]:
math.sqrt(-1)

ValueError: math domain error

In [88]:
np.sqrt(-1)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [89]:
np.math.sqrt(-1)

ValueError: math domain error

In [90]:
import cmath

In [91]:
cmath.sqrt(-1)

1j

In [93]:
np.sqrt(-1 + 0j)

1j

In [94]:
np.sum(np.arange(10))

45

In [95]:
sum(range(10))

45

In [96]:
np.prod(np.arange(3, 7))

360

In [99]:
np.cumprod(np.arange(1, 10))

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [98]:
np.median([1, -2, 3, -5, 7, 9])

2.0

In [100]:
np.mean([1, 2, 3, -5, -7])

-1.2

In [101]:
np.std([1, 2, 3, -4, -7])

3.847076812334269

In [102]:
np.nansum([1, 2, 3, np.nan, float('nan')])

6.0

In [103]:
np.sum([1, 2, 3, np.nan, float('nan')])

nan

In [104]:
np.nanmean([1, 2, 3, np.nan, float('nan')])

2.0

In [113]:
ma = np.ma.array([1,2,3,4], mask=[True, False, True, False],
                 fill_value=-100500)
ma

masked_array(data=[--, 2, --, 4],
             mask=[ True, False,  True, False],
       fill_value=-100500)

In [115]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a[5]

5

In [117]:
a[0:5]

array([0, 1, 2, 3, 4])

In [118]:
a[:5]

array([0, 1, 2, 3, 4])

In [120]:
s = '0123456789'
s[5:len(s)]

'56789'

In [121]:
s[5:]

'56789'

In [122]:
a[-1]

9

In [123]:
s[-len(s)]

'0'

In [124]:
s[-len(s) - 1]

IndexError: string index out of range

In [125]:
s[len(s)]

IndexError: string index out of range

In [126]:
a[2:8:2]

array([2, 4, 6])

In [127]:
a[::2]

array([0, 2, 4, 6, 8])

In [128]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [129]:
a[10:3:-1]

array([9, 8, 7, 6, 5, 4])

In [132]:
spisok1 = [1,2,3,4,5]
spisok2 = spisok1[::2]
spisok2[-1] = 100
spisok1

[1, 2, 3, 4, 5]

In [134]:
li = [1,2,3,4,5]
li[::2] = (-1, -3, -5)
li

[-1, 2, -3, 4, -5]

In [142]:
a = np.arange(10)
b = a[::2].copy()
b[-1] = 100
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
b.flags.owndata

True

In [138]:
a.flags.owndata

True

In [141]:
b.flags.owndata

False