In [5]:
%autosave 10
import numpy as np

Autosaving every 10 seconds


In [6]:
np.lookfor('date')

Search results for 'date'
-------------------------
numpy.datetime_data
    Get information about the step size of a date or time type.
numpy.is_busday
    Calculates which of the given dates are valid days, and which are not.
numpy.busday_count
    Counts the number of valid days between `begindates` and
numpy.datetime_as_string
    Convert an array of datetimes into an array of strings.
numpy.busday_offset
    First adjusts the date to fall on a valid day according to
numpy.chararray.setflags
    Set array flags WRITEABLE, ALIGNED, (WRITEBACKIFCOPY and UPDATEIFCOPY),
numpy.ndindex.__next__
    Standard iterator method, updates the index and returns the index
numpy.lib._iotools.NameValidator
    Object to validate a list of strings to use as field names.
numpy.diff
    Calculate the n-th discrete difference along the given axis.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.memmap
    Create a memory-map to an array stored in a *bin

In [8]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
a.size

6

In [10]:
len(a)

2

In [11]:
for row in a:
    print(row)

[1. 2. 3.]
[4. 5. 6.]


In [12]:
a[0][2]

3.0

In [13]:
a[0, 2]

3.0

In [14]:
for x in np.nditer(a):
    print(x)

1.0
2.0
3.0
4.0
5.0
6.0


In [15]:
a.flatten()

array([1., 2., 3., 4., 5., 6.])

In [16]:
for x in a.flat:
    print(x)

1.0
2.0
3.0
4.0
5.0
6.0


In [17]:
for i, x in np.ndenumerate(a):
    print(i, x)

(0, 0) 1.0
(0, 1) 2.0
(0, 2) 3.0
(1, 0) 4.0
(1, 1) 5.0
(1, 2) 6.0


In [18]:
a.shape

(2, 3)

In [19]:
a.ndim

2

In [20]:
a.size, a.shape, a.ndim

(6, (2, 3), 2)

In [21]:
assert 1 == 2

AssertionError: 

In [22]:
assert 1 == True

In [23]:
assert a.size == np.prod(a.shape)

In [24]:
assert len(a.shape) == a.ndim

In [26]:
flat_a = a.reshape(6)
flat_a, flat_a.shape, flat_a.flags.owndata

(array([1., 2., 3., 4., 5., 6.]), (6,), False)

In [27]:
a.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [28]:
a.transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [29]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
a.resize(4, 4)

In [31]:
a.shape

(4, 4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
np.resize(a, (2,2))

array([[0, 1],
       [2, 3]])

In [37]:
a = np.arange(16)
a.resize(2, 2)
a

array([[0, 1],
       [2, 3]])

In [39]:
a = np.arange(16)
b = a.reshape(2, 8)
a.resize(2, 2)

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [40]:
a = np.arange(16)
print(a.shape, a.ndim)
a.shape = (4, 4)
print(a.shape, a.ndim)
print(a)

(16,) 1
(4, 4) 2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [41]:
a = np.arange(16)
a.shape = (2, 2)

ValueError: cannot reshape array of size 16 into shape (2,2)

In [44]:
x = (16,)
type(x)

tuple

In [45]:
x = (16)
type(x)

int

In [46]:
a = np.arange(16)
a.reshape([2] * 4)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [47]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
2 * a

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [49]:
np.array([[1,1,2], [2,2,3]]) * a

array([[ 0,  1,  4],
       [ 6,  8, 15]])

In [50]:
np.array([1,2,3]) * a

array([[ 0,  2,  6],
       [ 3,  8, 15]])

In [51]:
np.array(2).ndim

0

In [52]:
np.array([0, 3]) * a

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [54]:
np.array([[0], [3]]) * a

array([[ 0,  0,  0],
       [ 9, 12, 15]])

In [55]:
np.array([[0], [3]])

array([[0],
       [3]])

In [56]:
column = np.array([0, 3])
column.T

array([0, 3])

In [57]:
column.reshape(2, 1) * a

array([[ 0,  0,  0],
       [ 9, 12, 15]])

In [58]:
column.reshape(-1, 1) * a

array([[ 0,  0,  0],
       [ 9, 12, 15]])

In [59]:
a = np.arange(16)
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
a.reshape(5, 3)

ValueError: cannot reshape array of size 16 into shape (5,3)

In [61]:
a.reshape(5, -1)

ValueError: cannot reshape array of size 16 into shape (5,newaxis)

In [62]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [63]:
column

array([0, 3])

In [65]:
a = np.arange(6).reshape(2, 3)

In [67]:
b = np.linspace(0, 1, 6)
b

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [69]:
c = b[:4]
c.shape

(4,)

In [71]:
c = b[0:b.shape[0]:2]
c = b[::2]
# for (int i = first; i < last; i += step) {}
c.shape, c

((3,), array([0. , 0.4, 0.8]))

In [72]:
b[1:5]

array([0.2, 0.4, 0.6, 0.8])

In [74]:
b[-2:0:-1]

array([0.8, 0.6, 0.4, 0.2])

In [75]:
b[5:1]

array([], dtype=float64)

In [76]:
c = b[:]
# c = b

In [77]:
b[:] = -5
b

array([-5., -5., -5., -5., -5., -5.])

In [80]:
b[:] = np.arange(6) ** 2

In [81]:
b

array([ 0.,  1.,  4.,  9., 16., 25.])

In [82]:
c1 = b[:, np.newaxis]
c2 = b.reshape(-1, 1)
assert c1.shape == c2.shape
c1.shape

(6, 1)

In [83]:
b[::-1, np.newaxis]

array([[25.],
       [16.],
       [ 9.],
       [ 4.],
       [ 1.],
       [ 0.]])

In [84]:
b[:, None]

array([[ 0.],
       [ 1.],
       [ 4.],
       [ 9.],
       [16.],
       [25.]])

In [85]:
assert np.newaxis is None

In [86]:
a2d = np.arange(16).reshape(4, 4)
a4d = a2d.reshape(2, 2, 2, 2)

In [87]:
a2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
a2d[3]

array([12, 13, 14, 15])

In [89]:
a2d[3, :]

array([12, 13, 14, 15])

In [90]:
a2d[3][-1]

15

In [91]:
a2d[:][3]

array([12, 13, 14, 15])

In [92]:
a2d[:, 3]

array([ 3,  7, 11, 15])

In [93]:
a2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
a2d[:, -1]

array([ 3,  7, 11, 15])

In [95]:
a2d[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [101]:
print(a2d)
a2d[::2, ::-2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 3,  1],
       [11,  9]])

In [102]:
a4d[0]

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [103]:
a4d[0, 0, ::-1, 0]

array([2, 0])

In [105]:
print(a4d)
print(a4d[:, :, :, 0])
print(a4d[..., 0])

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]
[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]


In [106]:
a4d[0, ..., 0]

array([[0, 2],
       [4, 6]])

In [107]:
a4d[0, ..., 0] = [-5, -6]
a4d

array([[[[-5,  1],
         [-6,  3]],

        [[-5,  5],
         [-6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [109]:
a = np.arange(5) ** 2
a

array([ 0,  1,  4,  9, 16])

In [110]:
np.sum(a[::2])

20

In [111]:
a[::2].sum()

20

In [112]:
np.sum(a[1::2])

10

In [114]:
a = np.arange(6, dtype=float).reshape(2, 3)
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [116]:
np.sum(np.sin(a), axis=1)

array([ 1.75076841, -1.57460676])

In [129]:
sin_j = np.sin(np.arange(a.shape[1]))
np.sum(a * sin_j, axis=1)

array([2.66006584, 7.91237107])

In [130]:
np.sum(np.sin(a) + 2 * np.cos(a))

0.1761616497223787

In [131]:
# double s = 0;
# for (int i = 0; i < a.size(); i++) {
#     s += sin(a[i]);
# }

In [132]:
?np.sin

In [133]:
a = np.array([1, 2, 3, 4])
bool_idx = np.array([True, True, False, True])
a[bool_idx]

array([1, 2, 4])

In [134]:
a = np.array([[1, 2], [3, 4]])
bool_idx = np.array([[True, True], [False, True]])
a[bool_idx]

array([1, 2, 4])

In [135]:
a[[True, False]]

array([[1, 2]])

In [136]:
a % 2 == 0

array([[False,  True],
       [False,  True]])

In [137]:
idx = a % 2 == 0
a[idx]

array([2, 4])

In [138]:
a = np.array([-1, 2, 3, -2, 5, -2, -1, 10, 77])
a[a > 0]

array([ 2,  3,  5, 10, 77])

In [139]:
b = a[a > 0]
b.flags.owndata

True

In [142]:
a = np.array([-1, 2, 3, -2, 5, -2, -1, 10, 77])
a[a < 0] = 0
a

array([ 0,  2,  3,  0,  5,  0,  0, 10, 77])

In [143]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [146]:
a[[True, False, True, True], ::2, np.newaxis]

array([[[ 0],
        [ 2]],

       [[ 8],
        [10]],

       [[12],
        [14]]])

In [147]:
bool_idx

array([[ True,  True],
       [False,  True]])

In [148]:
np.where(bool_idx)

(array([0, 0, 1]), array([0, 1, 1]))

In [149]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [150]:
a[np.array([0, 3])]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [151]:
# a[np.array[i1, i2], np.array[j1, j2]]
a[np.array([0, 3]), np.array([1, 2])]

array([ 1, 14])

In [152]:
a = np.array([1, 2, 3, 4, 5])
a[[0, 4, 1]]

array([1, 5, 2])

In [153]:
b = a[[0, 4, 1]]
b.flags.owndata

True

In [154]:
a[[0, 4, 1]] = 0
a

array([0, 0, 3, 4, 0])

In [155]:
a[[0, 1, 0, 2]] = [100, 101, 102, 103]
a

array([102, 101, 103,   4,   0])

In [157]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [161]:
np.diag(a, -1)

array([ 4,  9, 14])

In [162]:
a[np.arange(4), np.arange(4)]

array([ 0,  5, 10, 15])

In [163]:
np.tril(a)

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0],
       [12, 13, 14, 15]])

In [164]:
np.diag_indices_from(a)

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [165]:
np.tril_indices_from(a)

(array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 1, 0, 1, 2, 0, 1, 2, 3]))

In [166]:
np.r_[1:10, 0:1:11j, [4, 2, 1, 5]]

array([1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. , 0. , 0.1, 0.2, 0.3,
       0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 4. , 2. , 1. , 5. ])

In [167]:
np.vstack(([1, 2, 3], [6, 5, 2]))

array([[1, 2, 3],
       [6, 5, 2]])

In [168]:
np.emath.sqrt(-1)

1j

In [169]:
np.fft

<module 'numpy.fft' from '/opt/conda/lib/python3.6/site-packages/numpy/fft/__init__.py'>

In [172]:
np.dot([1, 2, 3], [5, 4, 2])
np.linalg.det
np.linalg.inv
np.linalg.solve
np.linalg.lstsq
np.array([5, 2, 1]) @ np.array([1, 2, 5])

14

In [173]:
np.random.rand(5, 2)

array([[0.50755507, 0.0211933 ],
       [0.43352176, 0.44631306],
       [0.23881999, 0.83024573],
       [0.74476418, 0.586479  ],
       [0.49286785, 0.48735588]])

In [174]:
np.random.normal(10, 3, 5)

array([12.01637482,  5.52106225,  7.5184058 , 12.74258662,  7.20651152])

In [175]:
np.testing

<module 'numpy.testing' from '/opt/conda/lib/python3.6/site-packages/numpy/testing/__init__.py'>

In [179]:
if np.all(np.array([1, 2, 3]) == np.array([1, 2, 4])):
    print('True')
else:
    print('False')

False


In [ ]:
np.array_equal
np.allclose