In [1]:
%autosave 20
import numpy as np

Autosaving every 20 seconds


In [12]:
a = np.array([1,2,3,4], dtype=np.complex)
a[0] = 1.5 + 3j
a

array([ 1.5+3.j,  2.0+0.j,  3.0+0.j,  4.0+0.j])

In [14]:
a = np.array([1,2,3,4], dtype=np.uint8)
a[0] = -1
a

array([255,   2,   3,   4], dtype=uint8)

In [15]:
a = np.array([1,2,3,4], dtype=np.float128)

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0., 1., 1./3.)

array([ 0.        ,  0.33333333,  0.66666667])

In [30]:
print(np.linspace(0., 1., 3))
print(np.logspace(0., 1., 3), 10**np.linspace(0.,1.,3))

[ 0.   0.5  1. ]
[  1.           3.16227766  10.        ] [  1.           3.16227766  10.        ]


In [35]:
np.empty(5, dtype=np.float)

array([  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,
         1.48219694e-323,   1.97626258e-323])

In [36]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [37]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
np.full(3, 7., dtype=np.complex)

array([ 7.+0.j,  7.+0.j,  7.+0.j])

In [42]:
a = np.arange(5)
b = np.empty_like(a, dtype=np.float)
print(a)
print(b)

[0 1 2 3 4]
[  0.00000000e+000   4.94065646e-324   9.88131292e-324   1.48219694e-323
   1.97626258e-323]


In [54]:
a = np.arange(10)
b = a[0:3]
b[0] = -100
print(b)
print(b.base)

[-100    1    2]
[-100    1    2    3    4    5    6    7    8    9]


In [83]:
a = np.arange(10)
print(a.data)
a += 3
print(a.data)
b = np.zeros_like(a)
a = b
a += 3
print(a, b)
print(a.data, b.data)

[3 3 3 3 3 3 3 3 3 3] [3 3 3 3 3 3 3 3 3 3]
<memory at 0x7fb2d4095e88> <memory at 0x7fb2d4095f48>


In [84]:
a = np.arange(10)
print(a.data)
a += 3
print(a.data)
b = np.zeros_like(a)
a[:] = b
a += 3
print(a, b)
print(a.data, b.data)

[3 3 3 3 3 3 3 3 3 3] [0 0 0 0 0 0 0 0 0 0]
<memory at 0x7fb2d4095e88> <memory at 0x7fb2d4095f48>


In [91]:
a = np.arange(10)
b = np.zeros(5)
a[:5] = b
print(a)
a[5:] = np.array([1])
print(a)
a[:] = b

[0 0 0 0 0 5 6 7 8 9]
[0 0 0 0 0 1 1 1 1 1]


ValueError: could not broadcast input array from shape (5) into shape (10)

In [97]:
a = np.arange(10)**2
b = a[np.array([1,2,1,0,1])]
print('b', b)
b[:] = -100
print('a', a)
print('b', b)

b [1 4 1 0 1]
a [ 0  1  4  9 16 25 36 49 64 81]
b [-100 -100 -100 -100 -100]


In [98]:
a = np.zeros(5)
a[[1,2,1,1]] += 1
print(a)

[ 0.  1.  1.  0.  0.]


In [105]:
a = np.arange(10)
b = (a % 2) == 0
print(b)
print(a[b])

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [111]:
a = np.random.rand(10) - 0.8
a[a < 0] = 100
print(a)

[ 100.          100.          100.          100.          100.          100.
  100.          100.          100.            0.15361538]
